<!doctype html><html><body style="margin:0;background:#f1f5f9;font-family:Arial,sans-serif;color:#0f172a"><div style="max-width:620px;margin:0 auto;padding:28px 16px"><div style="background:#059669;color:white;padding:24px;border-radius:16px 16px 0 0"><h1 style="margin:0;font-size:22px">Aquilizan Dental Clinic</h1></div><div style="background:white;padding:28px;border-radius:0 0 16px 16px">
@if($event === 'booking_received')
<h2>We received your appointment request.</h2><p>Hello {{ $entity->full_name }}, your requested time is being held pending review.</p><p><strong>Services:</strong> {{ $entity->service_names }}<br><strong>Requested date:</strong> {{ ($entity->requested_start_at ?? $entity->preferred_date)->setTimezone('Asia/Manila')->format('F j, Y') }}<br><strong>Requested time:</strong> {{ $entity->requested_start_at ? $entity->requested_start_at->setTimezone('Asia/Manila')->format('g:i A').'–'.$entity->requested_end_at->setTimezone('Asia/Manila')->format('g:i A') : ucfirst($entity->preferred_time_window) }}</p>
@elseif($event === 'appointment_cancelled')
<h2>Your appointment was cancelled.</h2><p>Hello {{ $entity->full_name }}, the appointment below has been cancelled and its time is no longer reserved.</p><p><strong>Services:</strong> {{ $entity->service_names }}<br><strong>Date:</strong> {{ $entity->appointment_date->format('F j, Y') }}<br><strong>Time:</strong> {{ $entity->appointment_time ?: 'Time to be arranged' }}<br><strong>Reason:</strong> {{ $entity->cancellation_reason }}</p>@if($entity->rescheduledAppointment)<p><strong>A new appointment request was created:</strong><br>{{ $entity->rescheduledAppointment->requested_start_at->setTimezone('Asia/Manila')->format('F j, Y, g:i A') }}–{{ $entity->rescheduledAppointment->requested_end_at->setTimezone('Asia/Manila')->format('g:i A') }}</p><p>This exact range is held pending confirmation.</p>@else<p>Please contact the clinic if you would like another schedule.</p>@endif
@elseif($event === 'appointment_reminder')
<h2>Your appointment is coming up.</h2><p>Hello {{ $entity->full_name }}, this is a friendly reminder about your upcoming dental appointment.</p><p><strong>Services:</strong> {{ $entity->service_names }}<br><strong>Date:</strong> {{ $entity->scheduled_start_at->setTimezone('Asia/Manila')->format('F j, Y') }}<br><strong>Time:</strong> {{ $entity->scheduled_start_at->setTimezone('Asia/Manila')->format('g:i A') }}@if($entity->scheduled_end_at)–{{ $entity->scheduled_end_at->setTimezone('Asia/Manila')->format('g:i A') }}@endif @if($entity->dentist)<br><strong>Dentist:</strong> {{ $entity->dentist->name }}@endif</p><p>Please contact the clinic as soon as possible if you need help with your appointment.</p>
@elseif($event === 'staff_credentials')
<h2>Your staff account is ready.</h2><p>Hello {{ $entity->name }}, an Aquilizan Dental Clinic {{ ucfirst($entity->role) }} account was created for you.</p><p><strong>Email:</strong> {{ $entity->email }}<br><strong>Temporary password:</strong> <code>{{ $secrets['temporary_password'] }}</code></p><p><a href="{{ $secrets['login_url'] }}">Sign in to your account</a>. You will be reminded to replace this temporary password.</p>
@else
<h2>Reset your password.</h2><p>We received a password reset request for your staff account.</p><p><a href="{{ $secrets['reset_url'] }}">Reset your password</a></p><p>This link expires in 60 minutes and can be used once. Ignore this message if you did not request it.</p>
@endif
@if(filled($clinic->phone) || filled($clinic->email))<hr style="border:0;border-top:1px solid #e2e8f0;margin:24px 0"><p style="font-size:13px;color:#64748b">{{ $clinic->address }}<br>{{ $clinic->phone }} @if(filled($clinic->email)) · {{ $clinic->email }} @endif</p>@endif
</div></div></body></html>
