@extends('layouts.patient')
@section('page_title', $invoice->invoice_number)

@section('content')
<div class="page-header print:hidden"><div><h1 class="page-title">{{ $invoice->payment_status === 'paid' ? 'Receipt' : 'Invoice' }}</h1><p class="page-subtitle">{{ $invoice->invoice_number }}</p></div><button onclick="window.print()" class="primary-action"><i class="fa-solid fa-print"></i> Print</button></div>
<div class="mx-auto max-w-2xl">
    <div id="receipt" class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div class="bg-emerald-500 px-8 py-8 text-white"><div class="flex items-start justify-between gap-6"><div><div class="flex items-center gap-3"><div class="flex h-10 w-10 items-center justify-center rounded-xl bg-white/20"><i class="fa-solid fa-tooth"></i></div><div class="font-bold text-lg">{{ $clinic->clinic_name ?: 'DentalCare' }}</div></div>@if($clinic->address)<p class="mt-2 text-xs text-emerald-100">{{ $clinic->address }}</p>@endif</div><div class="text-right"><div class="text-2xl font-bold">{{ $invoice->payment_status === 'paid' ? 'RECEIPT' : 'INVOICE' }}</div><div class="mt-1 font-mono text-sm text-emerald-100">{{ $invoice->invoice_number }}</div></div></div></div>
        <div class="px-8 py-6">
            <div class="mb-6 grid grid-cols-2 gap-6 border-b border-slate-100 pb-6 text-sm"><div><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Billed To</p><p class="mt-1 font-semibold text-slate-800">{{ $invoice->patient->name }}</p><p class="text-slate-500">{{ $invoice->patient->mobile ?: 'No mobile number' }}</p></div><div class="text-right"><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Invoice Date</p><p class="mt-1 font-semibold text-slate-800">{{ $invoice->invoice_date->format('F j, Y') }}</p>@if($invoice->due_date)<p class="mt-3 text-xs font-semibold uppercase tracking-wide text-slate-400">Due</p><p class="font-semibold text-slate-800">{{ $invoice->due_date->format('F j, Y') }}</p>@endif</div></div>
            <table class="mb-6 w-full text-sm"><thead><tr class="border-b border-slate-100 text-xs uppercase tracking-wide text-slate-400"><th class="pb-2 text-left">Description</th><th class="pb-2 text-center">Qty</th><th class="pb-2 text-right">Total</th></tr></thead><tbody>@foreach($invoice->items as $item)<tr class="border-b border-slate-50"><td class="py-3 text-slate-700">{{ $item->description }}</td><td class="py-3 text-center text-slate-500">{{ $item->qty }}</td><td class="py-3 text-right font-medium text-slate-800">PHP {{ number_format($item->qty * $item->price, 2) }}</td></tr>@endforeach</tbody></table>
            <div class="space-y-2 border-t border-slate-100 pt-4 text-sm"><div class="flex justify-between text-slate-500"><span>Subtotal</span><span>PHP {{ number_format($invoice->subtotal, 2) }}</span></div>@if($invoice->discount > 0)<div class="flex justify-between text-slate-500"><span>Discount</span><span>PHP {{ number_format($invoice->discount, 2) }}</span></div>@endif<div class="flex justify-between border-t pt-3 text-lg font-bold text-slate-800"><span>Total</span><span>PHP {{ number_format($invoice->total, 2) }}</span></div><div class="flex justify-between text-slate-500"><span>Amount Paid</span><span>PHP {{ number_format($invoice->amount_paid, 2) }}</span></div><div class="flex justify-between font-bold text-slate-800"><span>Remaining Balance</span><span>PHP {{ number_format($invoice->balance, 2) }}</span></div></div>
            @if($invoice->payments->isNotEmpty())<div class="mt-6"><p class="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-400">Payment History</p>@foreach($invoice->payments as $payment)<div class="flex justify-between border-b border-slate-100 py-2 text-sm"><span>{{ $payment->paid_at->format('M j, Y g:i A') }} · {{ $payment->method }}</span><strong>PHP {{ number_format($payment->amount, 2) }}</strong></div>@endforeach</div>@endif
        </div>
    </div>
</div>
@endsection
